services:
  postgres:
    image: postgres:15
    container_name: task-manager-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-manager-network

volumes:
  postgres_data:

networks:
  task-manager-network:
    driver: bridge
